name: 🛠 Build & Release

on:
  push:
    branches: [main, master]
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  android:
    uses: ./.github/workflows/android.yaml
